name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:

  build-exe:

    runs-on: windows-latest

    steps:

    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Instalar dependencias
      run: |
        pip install pandas
        pip install openpyxl
        pip install pillow
        pip install pyinstaller

    - name: Compilar EXE
      run: pyinstaller Bimsa_Cli.py --onefile --name ETLMensajero --add-data "logo_bimsa.jpg;."

    - name: Subir ejecutable
      uses: actions/upload-artifact@v4
      with:
        name: ETLMensajero
        path: dist/ETLMensajero.exe